version: "3"
services:
  db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: bq
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./db-data:/data/db
    restart: always
    networks:
      - private
    expose:
      - 27017
    ports:
      - 28017:27017
  node:
    image: node:20
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: mongodb://db:secret@localhost:27017/
      JWT_SECRET: xxxxxxxx
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: changeme
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
